# Generated by Django 3.2.15 on 2022-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20221002_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='depart_id',
            field=models.IntegerField(),
        ),
    ]
