# Generated by Django 3.2.15 on 2022-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_depart_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['department']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='depart_id',
        ),
    ]
