# Generated by Django 3.2.15 on 2022-10-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
