# Generated by Django 3.2.15 on 2022-09-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category_filter',
            field=models.CharField(choices=[('general', 'General'), ('animals', 'Animals'), ('architecture', 'Architecture'), ('baby', 'Baby'), ('commercial', 'Commercial'), ('fashion', 'Fashion'), ('landscape', 'Landscape'), ('portrait', 'Portrait'), ('wedding', 'Wedding'), ('sports', 'Sports')], default='general', max_length=32),
        ),
    ]
