# Generated by Django 3.2.15 on 2022-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_category_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='occupation',
            field=models.CharField(default='Photographer', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='category_filter',
            field=models.CharField(choices=[('General', 'General'), ('Animals', 'Animals'), ('Architecture', 'Architecture'), ('Baby', 'Baby'), ('Commercial', 'Commercial'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Sports', 'Sports'), ('Travel', 'Travel'), ('Wedding', 'Wedding')], default='General', max_length=32),
        ),
    ]
