# Generated by Django 3.2.15 on 2022-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20221007_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='occupation',
            new_name='skill_level',
        ),
    ]
